### ISSUE TITLE
Bibliography - vymyslet způsob vyhledávání

### ISSUE THREAD

**Issue by xtuzil** [xtuzil/PA193_TeamProject#13]

**Comment by xtuzil** [comment]
Před klíčovým slovem může bát číslo, tečka, mezery

Klíčový slova:
References
Referenced Literature
Bibliography
REFERENCE DOCUMENTS

začátek první - hranatý závorky
poté vždy musí sedět odsazení => Pokud nesedí, buď je tam něco vloženýho mezi nebo končí bibliography


problémy: 
konec stránky a pokračování na druhé 

např. 0879V4a_pdf.txt - rozhozený a něco mezitím

**Comment by tomas-slancar** [comment]
Kdyz naparsujem obsah, tak z neho by se dalo vycist, na jakych strankach je bibliography.
Tez by diky tomu slo pravdepodobne odhalit footer a text v nem (a tedy footer smazat z vyhledavani). Pak by se zmena odsazeni na dalsi strance dala odhalit.
